In [ ]:
# question 1
import sys

def relative_weight_on_earth(space_body, lb_weight):
    space_bodies = {"Sun": 27.01, "Mercury": 0.38, "Venus":0.91,
                    "Moon":0.166,  "Mars":0.38, "Jupiter":2.34,
                    "Saturn":1.06, "Uranus":0.92, "Neptune":1.19,
                   "Pluto":0.6}

    # print("From the list of items, select a space body:")
    # for key in space_bodies:
    #     print(f"\t{key}")
    # space_body = input("-> ")

    if space_body not in space_bodies.keys():
        print(f"{space_body} is not a valid option. exiting...")
        sys.exit()

    # weight = float(input("Enter a weight on Earth:"))
    kilo_weight_on_space_body = (lb_weight/2.2)*space_bodies[space_body]
    return kilo_weight_on_space_body

space_body_list = ["Sun", "Mercury", "Venus", "Moon", "Mars"]
space_weights = [1,2,3,4,5]

for space_body in space_body_list:
    index = space_body_list.index(space_body)
    kilo_weight_on_space_body = relative_weight_on_earth(space_body, space_weights[index])
    print(f"Earth lbs weight: {space_weights[index]}")
    print(f"{space_body} kilo weight: {kilo_weight_on_space_body}")
    print('\n')

Earth lbs weight: 1
Sun kilo weight: 12.277272727272727


Earth lbs weight: 2
Mercury kilo weight: 0.34545454545454546


Earth lbs weight: 3
Venus kilo weight: 1.240909090909091


Earth lbs weight: 4
Moon kilo weight: 0.3018181818181818


Earth lbs weight: 5
Mars kilo weight: 0.8636363636363635




In [ ]:
# question 2

class Product:
    def __init__(self, name, price, quantity):
        self.name = str(name)
        self.price = float(price)
        self.quantity = int(quantity)

    def __str__(self):
        return f"Name: {self.name}\n\tPrice: ${self.price: .2f}\n\tQuantity: {self.quantity}"

    def restock(self, amount):
        self.quantity += amount
        #print(f"quantity: {self.quantity}")

    def sell(self, amount):
        self.quantity -= amount
        if self.quantity < 0:
            print("insufficient stock")
            self.quantity += amount
        #print(f"quantity: {self.quantity}")

# ======= Testing code ========
# # defining variables
# name = "name"
# price = 0.00
# quantity = 0
# restock_amount = 1
# sell_amount = 2

# #class run
# product_class = Product(name, price, quantity)
# product_class.restock(restock_amount)
# product_class.sell(sell_amount)

# creating objects
product1 = Product("Laptop", 1200, 10)
product2 = Product("Smartphone", 800, 25)
product3 = Product("Headphones", 150, 50)

# Interacting with objects
print(product1)
print(product2)
print(product3)

product1.sell(3)
product2.sell(5)
product3.restock(30)

print("-----Post sell/restock---")
print(product1)
print(product2)
print(product3)

Name: Laptop
	Price: $ 1200.00
	Quantity: 10
Name: Smartphone
	Price: $ 800.00
	Quantity: 25
Name: Headphones
	Price: $ 150.00
	Quantity: 50
-----Post sell/restock---
Name: Laptop
	Price: $ 1200.00
	Quantity: 7
Name: Smartphone
	Price: $ 800.00
	Quantity: 20
Name: Headphones
	Price: $ 150.00
	Quantity: 80


In [ ]:
# question 3
import pandas as pd

# 3a
df_bos_1 = pd.read_csv("Boston.csv")
print(f"First 20 records of data frame:\n {df_bos_1.head(20)}\n")
# 3b
print(f"Column Names: \n{df_bos_1.columns}\n")
print("Index of column names:")
for column in df_bos_1.columns:
    print(f"{df_bos_1.columns.get_loc(column)} - {column}")

First 20 records of data frame:
     Unnamed: 0     crim    zn  indus  chas    nox     rm    age     dis  rad  \
0            1  0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1   
1            2  0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2   
2            3  0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2   
3            4  0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3   
4            5  0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3   
5            6  0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3   
6            7  0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5   
7            8  0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5   
8            9  0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5   
9           10  0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5   
10          11  0.22489  12.5   7.87     0  0.524  6.377   94.3  6.3467    5   
11     

In [ ]:
# question 4
import numpy as np
tax_column = np.array(df_bos_1["tax"])

print(f"Mean: {np.mean(tax_column)}")
print(f"Standard Deviation: {np.std(tax_column)}")

Mean: 408.2371541501976
Standard Deviation: 168.37049503938118


In [ ]:
# question 5
df_bos_2 = df_bos_1[df_bos_1.index != 20]
df_bos_2 = df_bos_2.iloc[9:,4:]

print(df_bos_2.head(20))
print(df_bos_2.tail())

    chas    nox     rm    age     dis  rad  tax  ptratio  lstat  medv
9      0  0.524  6.004   85.9  6.5921    5  311     15.2  17.10  18.9
10     0  0.524  6.377   94.3  6.3467    5  311     15.2  20.45  15.0
11     0  0.524  6.009   82.9  6.2267    5  311     15.2  13.27  18.9
12     0  0.524  5.889   39.0  5.4509    5  311     15.2  15.71  21.7
13     0  0.538  5.949   61.8  4.7075    4  307     21.0   8.26  20.4
14     0  0.538  6.096   84.5  4.4619    4  307     21.0  10.26  18.2
15     0  0.538  5.834   56.5  4.4986    4  307     21.0   8.47  19.9
16     0  0.538  5.935   29.3  4.4986    4  307     21.0   6.58  23.1
17     0  0.538  5.990   81.7  4.2579    4  307     21.0  14.67  17.5
18     0  0.538  5.456   36.6  3.7965    4  307     21.0  11.69  20.2
19     0  0.538  5.727   69.5  3.7965    4  307     21.0  11.28  18.2
21     0  0.538  5.965   89.2  4.0123    4  307     21.0  13.83  19.6
22     0  0.538  6.142   91.7  3.9769    4  307     21.0  18.72  15.2
23     0  0.538  5.8

In [ ]:
# problem 6
# Create a series called bos_tax that is obtained from the df_bos_1 data frame.  Display the last 10 observations.

#Not really sure what you mean here. You want the last ten entires but dont specify what column to make this a series.
#This is the last ten items
bos_tax = df_bos_1.iloc[-10:,:]
print(bos_tax)

#this is the last ten items of only the tax column (making it a series)
print("\n")
bos_tax = bos_tax["tax"]
print(bos_tax)




     Unnamed: 0     crim   zn  indus  chas    nox     rm   age     dis  rad  \
496         497  0.28960  0.0   9.69     0  0.585  5.390  72.9  2.7986    6   
497         498  0.26838  0.0   9.69     0  0.585  5.794  70.6  2.8927    6   
498         499  0.23912  0.0   9.69     0  0.585  6.019  65.3  2.4091    6   
499         500  0.17783  0.0   9.69     0  0.585  5.569  73.5  2.3999    6   
500         501  0.22438  0.0   9.69     0  0.585  6.027  79.7  2.4982    6   
501         502  0.06263  0.0  11.93     0  0.573  6.593  69.1  2.4786    1   
502         503  0.04527  0.0  11.93     0  0.573  6.120  76.7  2.2875    1   
503         504  0.06076  0.0  11.93     0  0.573  6.976  91.0  2.1675    1   
504         505  0.10959  0.0  11.93     0  0.573  6.794  89.3  2.3889    1   
505         506  0.04741  0.0  11.93     0  0.573  6.030  80.8  2.5050    1   

     tax  ptratio  lstat  medv  
496  391     19.2  21.14  19.7  
497  391     19.2  14.10  18.3  
498  391     19.2  12.92  21.2 

In [ ]:
# problem 7

employees = {
    'EmployeeID': [1, 2, 3, 4, 5],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'DepartmentID': [101, 102, 101, 103, 102]
}
departments = {
    'DepartmentID': [101, 102, 103],
    'DepartmentName': ['HR', 'IT', 'Finance']
}
df_employees = pd.DataFrame(employees)
df_departments = pd.DataFrame(departments)

# 7a
# merge the two DFs on DepartmentID column to get a dataframe called
# df_merged that includes employee names and their department names
#df_employees_mod = df_employees.assign(key=df_employees.groupby("DepartmentID").cumcount())
#df_departments_mod = df_departments.assign(key=df_departments.groupby("DepartmentID").cumcount())



#df_merged = pd.merge(df_employees_mod, df_departments_mod, how="outer", on=["DepartmentID","key"]).sort_values("EmployeeID")
#df_merged = df_merged.drop(columns="key")
# for myself later:
#filling NaN:
    # This line makes a Series from a groupby-object that groups each unique DepartmentID with the
    # DepartmentName that is in the shared row. (ex: 101 is grouped with HR and NaN)
    # Printing out the groupby-object does nothing, so the ".first()" is used to grab the first
    # value that is not NaN and turn it into a Series. (ex: 101 only has HR)
#df_groupby = df_merged.groupby(by="DepartmentID")["DepartmentName"].first()

#replacing original data with NaN filled
    # This line replaces the "DepartmentName" column in df_merged with a Series.
    # The replacement Series uses the groups from the df_groupby Series to map (match)
    # indexes to values in the df_merged["DepartmentID"] Series.
    # (ex: 101 is replaced with HR)
#df_merged["DepartmentName"] = df_merged["DepartmentID"].map(df_groupby)

# ************** This line here achieves everything above *******************
df_merged = pd.merge(df_employees, df_departments, on="DepartmentID")
print(df_merged)

# 7b
# find out which employees belong to the IT department

df_merged_IT = df_merged[df_merged["DepartmentName"] == "IT"]
print(df_merged_IT)

# 7c
# create a Dataframe showing the count of employees in each department (hint: lookup groupby)
df_count_of_employees = df_merged.groupby(by="DepartmentID").size()
print(df_count_of_employees)







   EmployeeID Employee  DepartmentID DepartmentName
0           1    Alice           101             HR
1           2      Bob           102             IT
2           3  Charlie           101             HR
3           4    David           103        Finance
4           5      Eva           102             IT
   EmployeeID Employee  DepartmentID DepartmentName
1           2      Bob           102             IT
4           5      Eva           102             IT
DepartmentID
101    2
102    2
103    1
dtype: int64


In [ ]:
# problem 8
array_of_integers = np.array(range(1,21))
print(array_of_integers)
reshaped_array = np.reshape(array_of_integers, newshape=(4,5))
print(reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
# problem 9
array_of_ones = np.ones((3,3))
print(array_of_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# problem 10
M1 = np.array([[2, 4],
               [5, -7]])
M2 = np.array([[6,12],
               [10,-8]])
M3 = np.dot(M1,M2)
M4 = np.linalg.inv(M3)

print(M3)
print(M4)

[[ 52  -8]
 [-40 116]]
[[0.02030812 0.00140056]
 [0.0070028  0.00910364]]
